In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1 = np.arange(9).reshape(3,3)

arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [4]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series([3,4],index=['X','Y'])

In [6]:
ser1

T    0
U    1
V    2
dtype: int64

In [7]:
ser2

X    3
Y    4
dtype: int64

In [8]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [9]:
pd.concat([ser1,ser2],axis=1) #It creates a dataframe

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [10]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [11]:
dframe1 = DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])

In [12]:
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [13]:
dframe1

X         Y         Z
0 -1.226200 -0.663807  0.885900
1 -0.222614 -1.708184 -1.751517
2 -0.161002  0.565125 -2.221259
3  0.127497 -0.281552 -0.042427

In [14]:
dframe2

Y         Q         X
0  1.193675  0.575693 -1.934243
1  0.450244 -0.839112 -1.529538
2 -0.193314  0.505474 -0.195782

In [15]:
pd.concat([dframe1,dframe2])

Q         X         Y         Z
0       NaN -1.226200 -0.663807  0.885900
1       NaN -0.222614 -1.708184 -1.751517
2       NaN -0.161002  0.565125 -2.221259
3       NaN  0.127497 -0.281552 -0.042427
0  0.575693 -1.934243  1.193675       NaN
1 -0.839112 -1.529538  0.450244       NaN
2  0.505474 -0.195782 -0.193314       NaN

In [16]:
pd.concat([dframe1,dframe2],ignore_index=True)

Q         X         Y         Z
0       NaN -1.226200 -0.663807  0.885900
1       NaN -0.222614 -1.708184 -1.751517
2       NaN -0.161002  0.565125 -2.221259
3       NaN  0.127497 -0.281552 -0.042427
4  0.575693 -1.934243  1.193675       NaN
5 -0.839112 -1.529538  0.450244       NaN
6  0.505474 -0.195782 -0.193314       NaN